### ISSUE TITLE
Support for older PHP versions

### ISSUE THREAD

**Issue by enricodias** [reyesoft/mercadopago#12]
Is there any specific issue preventing this from work with older php versions and older endroid/qr-code versions? mercadopago/dx-php works with php >= 5.6

This package requires php >= 7.1

**Comment by pablorsk** [comment]
sorry, but the code was developed with types (check https://www.w3schools.com/php7/php7_datatypes.asp). If you change composer.json to 5.6, you'll have problems with functions calls.
